### ISSUE TITLE
More explanation for the config

### ISSUE THREAD

**Issue by pingshunhuang** [ahmadawais/shades-of-purple-hyper#1]
Could you please document a step by step process to make the terminal look exactly like what you have in the screenshot gif?

I install the extension and all it does is just change the background. It's not remotely close to what you showed in the gif which has `powerline`, `autocomplete` etc. Thanks.

**Comment by ahmadawais** [comment]
I'm thinking of making a small course on that 👍  So many folks asked for it.

But for now you can use my Shades of Purple theme for your ZSH shell present here to get that https://github.com/ahmadawais/shades-of-purple-hyper

**Comment by nullraven0** [comment]
Hi hi, 
I wrote a short article on Medium that shows the process of customisation step by step. At the end of the article, your terminal would look exactly like what Ahmad has shown. You can read it here: 
https://medium.com/@mehran.mehri/terminal-customisation-hyper-zsh-some-modification-c0a41f808209

**Comment by ahmadawais** [comment]
@1mp3rium thanks for writing that. Peace! ✌️
