### ISSUE TITLE
prompt is not same

### ISSUE THREAD

**Issue by himanshuvashist** [ahmadawais/shades-of-purple-hyper#2]
I am using hyper in windows and i installed shades-of-purple-hyper manually , i can see change in theme ,it became purple but my promt is not looking like yours.

![hyper](https://user-images.githubusercontent.com/35025815/46664853-ca7aef80-cbdf-11e8-88e8-9b8fc9e52690.png)

**Comment by ahmadawais** [comment]
That's my Zsh + Oh My Zsh + iTerm2 setup.

You should read this and use my 🦄 Shades of Purple theme for Zsh in there https://github.com/ahmadawais/Shades-of-Purple-iterm2

After that your terminal will look the same. I got your back.
